[tool.poetry]
name = "malayallama"
version = "0.1.0"
description = ""
authors = ["aneesh-aparajit <aneeshaparajit.g2002@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
transformers = "^4.36.2"
pandas = "^2.1.4"
peft = "^0.7.1"
trl = "^0.7.10"
sentencepiece = "^0.1.99"
python-dotenv = "^1.0.0"
dask = "^2024.1.0"
googletrans = "^3.0.0"
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
